apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-svc
  template:
    metadata:
      labels:
        app: neo4j-svc
    spec:
      containers:
        - name: neo4j-svc
          image: recommendationengine.azurecr.io/samples/neo4j:latest
          ports:
            - containerPort: 3010 
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-svc
  namespace: default
  labels:
    app: neo4j-svc
spec:
  selector:
    app: neo4j-svc
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3010
  type: LoadBalancer            
